const $ = s => document.querySelector(s);
const API = "/cgi-bin/khnc-api", STATE = "/cgi-bin/khnc-state-api", POLICY = "/cgi-bin/khnc-policy-api";
let raw = {}, state = {}, policies = {}, devices = [], currentFilter = "all";
const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const mac = v => String(v || "").toLowerCase();
function defaults(){return {scheduleEnabled:true,override:"schedule",periods:{weekday:{enabled:true,mode:"allow",allDay:false,start:"10:00",end:"22:00",limitMinutes:180},weekend:{enabled:true,mode:"allow",allDay:false,start:"09:00",end:"22:00",limitMinutes:300}}};}
function policyFor(value){const d=defaults(), p=value||{}; return {...d,...p,periods:{weekday:{...d.periods.weekday,...(p.periods?.weekday||{})},weekend:{...d.periods.weekend,...(p.periods?.weekend||{})}}};}
function connectionIndex(data){const wifi=new Map(), wired=new Set(); for(const radio of data.wifi||[]) for(const c of radio.clients||[]) wifi.set(mac(c.mac),{ssid:c.ssid||radio.ssid||"Wi-Fi",signal:c.signal,band:radio.band||""}); for(const e of data.ethernet||[]) wired.add(mac(e.mac)); return {wifi,wired};}
function makeDevices(){const index=connectionIndex(raw), prefs=state.prefs||{}; const rows=new Map(); for(const lease of raw.leases||[]) rows.set(mac(lease.mac),lease); Object.entries(prefs).forEach(([m,p])=>{if((p.registered||p.managed)&&!p.deleted&&!rows.has(mac(m)))rows.set(mac(m),{mac:m,ip:"-",hostname:p.displayName||p.name||"등록 기기"});}); devices=[...rows.values()].filter(d=>!prefs[mac(d.mac)]?.deleted).map(d=>{const m=mac(d.mac),p=prefs[m]||{},w=index.wifi.get(m),wired=index.wired.has(m);return {mac:m,name:p.displayName||p.name||d.hostname||"이름 없는 기기",ip:d.ip||"-",online:!!w||wired,connection:w?"wifi":wired?"wired":"offline",ssid:w?.ssid||"",signal:w?.signal,group:p.group||"미지정",parent:!!p.parentMode,registered:!!(p.registered||p.managed)};});}
function icon(d){return d.connection==="wifi"?"⌁":d.connection==="wired"?"⌘":"○"}
function renderHome(){const online=devices.filter(d=>d.online),wifi=online.filter(d=>d.connection==="wifi"),wired=online.filter(d=>d.connection==="wired"); $("#homeOnline").textContent=`${online.length} devices online`; $("#homeUpdated").textContent=`${new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})} updated`; $("#summaryCards").innerHTML=[["Registered",devices.filter(d=>d.registered).length,"all"],["Online",online.length,"online"],["Wi-Fi",wifi.length,"wifi"],["LAN",wired.length,"wired"]].map(([n,v,f])=>`<button data-home-filter="${f}"><span>${n}</span><strong>${v}</strong></button>`).join(""); document.querySelectorAll("[data-home-filter]").forEach(b=>b.onclick=()=>showView("devices",b.dataset.homeFilter)); const sys=raw.system||{}; $("#routerStatus").textContent=sys.hostname||"OpenWrt"; $("#routerStatus").className="status good"; $("#networkInfo").innerHTML=`<div><span>Router</span><strong>${esc(sys.model||"OpenWrt")}</strong></div><div><span>Wi-Fi clients</span><strong>${wifi.length}</strong></div><div><span>LAN clients</span><strong>${wired.length}</strong></div><div><span>Known devices</span><strong>${devices.length}</strong></div>`;}
function renderDevices(){const q=$("#deviceSearch").value.trim().toLowerCase(); const rows=devices.filter(d=>(currentFilter==="all"||currentFilter==="online"&&d.online||d.connection===currentFilter)&&`${d.name} ${d.ip} ${d.mac}`.toLowerCase().includes(q)); $("#deviceList").innerHTML=rows.length?rows.map(d=>`<article class="device-card"><div class="device-top"><i class="device-icon">${icon(d)}</i><div class="device-title"><b>${esc(d.name)}</b><small>${esc(d.ip)} · ${esc(d.mac)}</small></div><span class="badge ${d.online?"online":""}">${d.online?"ONLINE":"OFFLINE"}</span></div><div class="device-meta"><div><span>Connection</span><strong>${d.connection==="wifi"?esc(d.ssid||"Wi-Fi"):d.connection==="wired"?"LAN":"-"}</strong></div><div><span>Group</span><strong>${esc(d.group)}</strong></div></div></article>`).join(""):`<p class="empty">조건에 맞는 기기가 없습니다.</p>`;}
function summary(p){if(!p.scheduleEnabled)return "Schedule off";if(p.override==="allow")return "Always allow";if(p.override==="block")return "Blocked now";const a=p.periods.weekday,b=p.periods.weekend;const text=x=>x.allDay?"24 hours":`${x.start}–${x.end} · ${x.limitMinutes/60}h`;return `Weekday ${text(a)} · Weekend ${text(b)}`;}
function renderParent(){const rows=devices.filter(d=>d.parent); $("#parentList").innerHTML=rows.length?rows.map(d=>{const p=policyFor(policies[d.mac]);return `<article class="parent-card"><div><h2>${esc(d.name)}</h2><p>${esc(summary(p))}</p></div><button data-policy="${d.mac}">Manage</button></article>`}).join(""):`<p class="empty">Parent Mode에 등록된 기기가 없습니다.<br>Desktop KHNC에서 기기를 등록하세요.</p>`;document.querySelectorAll("[data-policy]").forEach(b=>b.onclick=()=>openPolicy(b.dataset.policy));}
function periodField(key,title,p){return `<section class="period" data-period="${key}"><h3>${title}</h3><label class="toggle"><span>Enable</span><input data-key="enabled" type="checkbox" ${p.enabled!==false?"checked":""}></label><label class="toggle"><span>24 hours</span><input data-key="allDay" type="checkbox" ${p.allDay?"checked":""}></label><div class="time-grid"><label>Start<input data-key="start" type="time" value="${p.start}"></label><label>End<input data-key="end" type="time" value="${p.end}"></label></div><label class="field"><span>Continuous use (hours)</span><input data-key="hours" type="number" min="0.5" max="24" step="0.5" value="${p.limitMinutes/60}"></label></section>`;}
function openPolicy(m){const d=devices.find(x=>x.mac===m),p=policyFor(policies[m]); $("#policyMac").value=m;$("#policyTitle").textContent=`${d?.name||m} Schedule`;$("#scheduleEnabledMobile").checked=p.scheduleEnabled!==false;$("#overrideMobile").value=p.override;$("#periodFields").innerHTML=periodField("weekday","Weekday",p.periods.weekday)+periodField("weekend","Weekend",p.periods.weekend);$("#policyDialog").showModal();}
async function savePolicy(e){e.preventDefault();const m=$("#policyMac").value,old=policyFor(policies[m]),periods={};document.querySelectorAll(".period").forEach(row=>{const get=k=>row.querySelector(`[data-key="${k}"]`);periods[row.dataset.period]={enabled:get("enabled").checked,allDay:get("allDay").checked,mode:old.periods[row.dataset.period].mode,start:get("start").value||"00:00",end:get("end").value||"00:00",limitMinutes:Math.round(Math.max(.5,Math.min(24,Number(get("hours").value||1)))*60)}});policies[m]={...old,scheduleEnabled:$("#scheduleEnabledMobile").checked,override:$("#overrideMobile").value,periods,updatedAt:Date.now()};const payload={policies:Object.entries(policies).map(([mac,p])=>({mac,...p}))};try{const r=await fetch(POLICY,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok||data.ok===false)throw Error(data.error||"저장 실패");$("#policyDialog").close();renderParent();}catch(err){alert(`정책 저장 실패: ${err.message}`)}}
function showView(view,filter){if(filter){currentFilter=filter;document.querySelectorAll(".filter").forEach(b=>b.classList.toggle("active",b.dataset.filter===filter));renderDevices()}const names={home:"Home",devices:"Devices",parent:"Parent Mode",more:"More"};$("#pageTitle").textContent=names[view];document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`${view}View`));document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));}
async function load(){try{const [a,s,p,v]=await Promise.all([fetch(`${API}?_=${Date.now()}`),fetch(`${STATE}?_=${Date.now()}`),fetch(`${POLICY}?_=${Date.now()}`),fetch(`./version.json?_=${Date.now()}`)]);raw=await a.json();state=s.ok?await s.json():{};const pd=await p.json();policies=Object.fromEntries((pd.policies||[]).map(x=>{const {mac,...rest}=x;return [String(mac).toLowerCase(),rest]}));const version=await v.json();$("#mobileBuild").textContent=`v${version.version} · ${version.build}`;makeDevices();renderHome();renderDevices();renderParent();$("#notice").classList.add("hidden");}catch(err){$("#notice").textContent=`공유기 정보를 읽지 못했습니다: ${err.message}`;$("#notice").classList.remove("hidden")}}
document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));renderDevices()});$("#deviceSearch").oninput=renderDevices;$("#refresh").onclick=load;$("#closePolicy").onclick=()=>$("#policyDialog").close();$("#policyForm").onsubmit=savePolicy;$("#desktopLink").href=`http://${location.hostname}:8881`;$("#mobileAddress").textContent=`http://${location.host}`;load();
